version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.14.0-krypton
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.14.0-krypton
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "9999:5900"
  firefox:
    image: selenium/node-firefox-debug:3.14.0-krypton
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "9998:5900"
